### ISSUE TITLE
Change kubectl apply line to reference raw file not html on README

### ISSUE THREAD

**Issue by lachlan-b** [weaveworks-plugins/scope-iowait#7]
> If you want to use the Scope IOWait plugin in an already set up Kubernetes cluster with Weave Scope running on it, you just need to:

change
https://github.com/weaveworks-plugins/scope-iowait/tree/master/deployments/k8s-iowait.yaml
->>
https://raw.githubusercontent.com/weaveworks-plugins/scope-iowait/master/deployments/k8s-iowait.yaml

Weave scope is cool:)

**Comment by alban** [comment]
@lachlan-b: thanks for reporting! Do you want to make a PR for this?

There was a similar fix in another plugin: https://github.com/weaveworks-plugins/scope-http-statistics/pull/10
